# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SocialLogin' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SocialLogin
	pod 'KakaoSDK'

  target 'SocialLoginTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SocialLoginUITests' do
    # Pods for testing
  end

end
